### ISSUE TITLE
iPhone 13 ios 16.1.2 facetime only video call 

### ISSUE THREAD

**Issue by Echtar** [PARKasd/locchange#1]
I have iphone 13 ios 16.1.2 bought from china that facetime video only , and i tried your app but it didn’t work with facetime and its still only videocall

**Comment by PARKasd** [comment]
Did you rebooted your phone? If not do it

**Comment by Echtar** [comment]
> Did you rebooted your phone? If not do it

Yea sir i did

**Comment by Echtar** [comment]
I think its not possible to enable audio on facetime because its server side not just from device

**Comment by PARKasd** [comment]
> I think its not possible to enable audio on facetime because its server side not just from device

I'll check it out ASAP. Maybe several modifications might needed for that

**Comment by abxyap** [comment]
> 

True me,Its impossible to active facetime audio by modifing com.apple.MobileGestalt.plist

**Comment by PARKasd** [comment]
No plan to find the way out to mock this. also, no MDC iphone available for me to test
