### ISSUE TITLE
Is it still working? 

### ISSUE THREAD

**Issue by Urieeeeeelp** [PARKasd/locchange#5]
it still works? when I try to use it I get a dialog box with "nothing" or "respiring".

**Comment by PARKasd** [comment]
Whats your iOS version?

**Comment by Urieeeeeelp** [comment]
iOS 17.4.1

**Comment by Urieeeeeelp** [comment]
...

**Comment by PARKasd** [comment]
As you know, this app uses CVE 2022 46689 vuln. This only supports under 16.1.2
